yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "styled-components@*":
    dependencies:
      "babel-plugin-macros": "*"
  "microbundle-crl@*":
    dependencies:
      "@babel/plugin-transform-regenerator": "*"